default:
  - step: &build-step
      name: Build React App
      runs-on:
        - "self.hosted"
        - "windows"
      script:
        - npm install
        - npm run build:stage
        - powershell -Command "New-Item -ItemType Directory -Force -Path ./publish"
        - powershell -Command "Copy-Item -Path ./dist/* -Destination ./publish/ -Recurse -Force"
      artifacts:
        - publish/**

pipelines:
  branches:
    Stage:
      - step: *build-step
      - step:
          name: Stop IIS
          runs-on:
            - "self.hosted"
            - "windows"
          script:
            - powershell -Command "Import-Module WebAdministration"
            - powershell -Command "if ((Get-WebAppPoolState $env:STAGE_REACT_APPPOOL).Value -ne 'Stopped') { Stop-WebAppPool -Name $env:STAGE_REACT_APPPOOL }"
            - powershell -Command "if ((Get-Website $env:STAGE_REACT_SITE).State -ne 'Stopped') { Stop-Website -Name $env:STAGE_REACT_SITE }"
            - powershell -Command "Start-Sleep -Seconds 5"
      - step:
          name: Publish
          runs-on:
            - "self.hosted"
            - "windows"
          script:
            - powershell -Command "Copy-Item -Path ./publish/* -Destination '$env:STAGE_REACT_APP_PATH' -Recurse -Force"
      - step:
          name: Deploy
          deployment: staging
          runs-on:
            - "self.hosted"
            - "windows"
          script:
            - powershell -Command "if ((Get-WebAppPoolState $env:STAGE_REACT_APPPOOL).Value -ne 'Started') { Start-WebAppPool -Name $env:STAGE_REACT_APPPOOL }"
            - powershell -Command "if ((Get-Website $env:STAGE_REACT_SITE).State -ne 'Started') { Start-Website -Name $env:STAGE_REACT_SITE }"

definitions:
  caches:
    node: node_modules
