/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appUnauthorizedRouteImport } from './routes/(app)/unauthorized'
import { Route as appUploadContractsIndexRouteImport } from './routes/(app)/upload-contracts/index'
import { Route as appClosedContractsIndexRouteImport } from './routes/(app)/closed-contracts/index'
import { Route as appAddContractsIndexRouteImport } from './routes/(app)/add-contracts/index'
import { Route as appActiveContractsIndexRouteImport } from './routes/(app)/active-contracts/index'
import { Route as appInstallmentTransactionIdRouteImport } from './routes/(app)/installment/$transactionId'
import { Route as appAddContractsContractIdRouteImport } from './routes/(app)/add-contracts/$contractId'
import { Route as appCollectionsDelinquentContractsIndexRouteImport } from './routes/(app)/collections/delinquent-contracts/index'
import { Route as appCollectionsDelinquentContractsIdRouteImport } from './routes/(app)/collections/delinquent-contracts/$id'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appUnauthorizedRoute = appUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => appRouteRoute,
} as any)
const appUploadContractsIndexRoute = appUploadContractsIndexRouteImport.update({
  id: '/upload-contracts/',
  path: '/upload-contracts/',
  getParentRoute: () => appRouteRoute,
} as any)
const appClosedContractsIndexRoute = appClosedContractsIndexRouteImport.update({
  id: '/closed-contracts/',
  path: '/closed-contracts/',
  getParentRoute: () => appRouteRoute,
} as any)
const appAddContractsIndexRoute = appAddContractsIndexRouteImport.update({
  id: '/add-contracts/',
  path: '/add-contracts/',
  getParentRoute: () => appRouteRoute,
} as any)
const appActiveContractsIndexRoute = appActiveContractsIndexRouteImport.update({
  id: '/active-contracts/',
  path: '/active-contracts/',
  getParentRoute: () => appRouteRoute,
} as any)
const appInstallmentTransactionIdRoute =
  appInstallmentTransactionIdRouteImport.update({
    id: '/installment/$transactionId',
    path: '/installment/$transactionId',
    getParentRoute: () => appRouteRoute,
  } as any)
const appAddContractsContractIdRoute =
  appAddContractsContractIdRouteImport.update({
    id: '/add-contracts/$contractId',
    path: '/add-contracts/$contractId',
    getParentRoute: () => appRouteRoute,
  } as any)
const appCollectionsDelinquentContractsIndexRoute =
  appCollectionsDelinquentContractsIndexRouteImport.update({
    id: '/collections/delinquent-contracts/',
    path: '/collections/delinquent-contracts/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appCollectionsDelinquentContractsIdRoute =
  appCollectionsDelinquentContractsIdRouteImport.update({
    id: '/collections/delinquent-contracts/$id',
    path: '/collections/delinquent-contracts/$id',
    getParentRoute: () => appRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof appIndexRoute
  '/unauthorized': typeof appUnauthorizedRoute
  '/login': typeof authLoginRoute
  '/add-contracts/$contractId': typeof appAddContractsContractIdRoute
  '/installment/$transactionId': typeof appInstallmentTransactionIdRoute
  '/active-contracts': typeof appActiveContractsIndexRoute
  '/add-contracts': typeof appAddContractsIndexRoute
  '/closed-contracts': typeof appClosedContractsIndexRoute
  '/upload-contracts': typeof appUploadContractsIndexRoute
  '/collections/delinquent-contracts/$id': typeof appCollectionsDelinquentContractsIdRoute
  '/collections/delinquent-contracts': typeof appCollectionsDelinquentContractsIndexRoute
}
export interface FileRoutesByTo {
  '/unauthorized': typeof appUnauthorizedRoute
  '/login': typeof authLoginRoute
  '/': typeof appIndexRoute
  '/add-contracts/$contractId': typeof appAddContractsContractIdRoute
  '/installment/$transactionId': typeof appInstallmentTransactionIdRoute
  '/active-contracts': typeof appActiveContractsIndexRoute
  '/add-contracts': typeof appAddContractsIndexRoute
  '/closed-contracts': typeof appClosedContractsIndexRoute
  '/upload-contracts': typeof appUploadContractsIndexRoute
  '/collections/delinquent-contracts/$id': typeof appCollectionsDelinquentContractsIdRoute
  '/collections/delinquent-contracts': typeof appCollectionsDelinquentContractsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/unauthorized': typeof appUnauthorizedRoute
  '/(auth)/login': typeof authLoginRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/add-contracts/$contractId': typeof appAddContractsContractIdRoute
  '/(app)/installment/$transactionId': typeof appInstallmentTransactionIdRoute
  '/(app)/active-contracts/': typeof appActiveContractsIndexRoute
  '/(app)/add-contracts/': typeof appAddContractsIndexRoute
  '/(app)/closed-contracts/': typeof appClosedContractsIndexRoute
  '/(app)/upload-contracts/': typeof appUploadContractsIndexRoute
  '/(app)/collections/delinquent-contracts/$id': typeof appCollectionsDelinquentContractsIdRoute
  '/(app)/collections/delinquent-contracts/': typeof appCollectionsDelinquentContractsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unauthorized'
    | '/login'
    | '/add-contracts/$contractId'
    | '/installment/$transactionId'
    | '/active-contracts'
    | '/add-contracts'
    | '/closed-contracts'
    | '/upload-contracts'
    | '/collections/delinquent-contracts/$id'
    | '/collections/delinquent-contracts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/unauthorized'
    | '/login'
    | '/'
    | '/add-contracts/$contractId'
    | '/installment/$transactionId'
    | '/active-contracts'
    | '/add-contracts'
    | '/closed-contracts'
    | '/upload-contracts'
    | '/collections/delinquent-contracts/$id'
    | '/collections/delinquent-contracts'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/unauthorized'
    | '/(auth)/login'
    | '/(app)/'
    | '/(app)/add-contracts/$contractId'
    | '/(app)/installment/$transactionId'
    | '/(app)/active-contracts/'
    | '/(app)/add-contracts/'
    | '/(app)/closed-contracts/'
    | '/(app)/upload-contracts/'
    | '/(app)/collections/delinquent-contracts/$id'
    | '/(app)/collections/delinquent-contracts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/unauthorized': {
      id: '/(app)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof appUnauthorizedRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/upload-contracts/': {
      id: '/(app)/upload-contracts/'
      path: '/upload-contracts'
      fullPath: '/upload-contracts'
      preLoaderRoute: typeof appUploadContractsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/closed-contracts/': {
      id: '/(app)/closed-contracts/'
      path: '/closed-contracts'
      fullPath: '/closed-contracts'
      preLoaderRoute: typeof appClosedContractsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/add-contracts/': {
      id: '/(app)/add-contracts/'
      path: '/add-contracts'
      fullPath: '/add-contracts'
      preLoaderRoute: typeof appAddContractsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/active-contracts/': {
      id: '/(app)/active-contracts/'
      path: '/active-contracts'
      fullPath: '/active-contracts'
      preLoaderRoute: typeof appActiveContractsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/installment/$transactionId': {
      id: '/(app)/installment/$transactionId'
      path: '/installment/$transactionId'
      fullPath: '/installment/$transactionId'
      preLoaderRoute: typeof appInstallmentTransactionIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/add-contracts/$contractId': {
      id: '/(app)/add-contracts/$contractId'
      path: '/add-contracts/$contractId'
      fullPath: '/add-contracts/$contractId'
      preLoaderRoute: typeof appAddContractsContractIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/collections/delinquent-contracts/': {
      id: '/(app)/collections/delinquent-contracts/'
      path: '/collections/delinquent-contracts'
      fullPath: '/collections/delinquent-contracts'
      preLoaderRoute: typeof appCollectionsDelinquentContractsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/collections/delinquent-contracts/$id': {
      id: '/(app)/collections/delinquent-contracts/$id'
      path: '/collections/delinquent-contracts/$id'
      fullPath: '/collections/delinquent-contracts/$id'
      preLoaderRoute: typeof appCollectionsDelinquentContractsIdRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appUnauthorizedRoute: typeof appUnauthorizedRoute
  appIndexRoute: typeof appIndexRoute
  appAddContractsContractIdRoute: typeof appAddContractsContractIdRoute
  appInstallmentTransactionIdRoute: typeof appInstallmentTransactionIdRoute
  appActiveContractsIndexRoute: typeof appActiveContractsIndexRoute
  appAddContractsIndexRoute: typeof appAddContractsIndexRoute
  appClosedContractsIndexRoute: typeof appClosedContractsIndexRoute
  appUploadContractsIndexRoute: typeof appUploadContractsIndexRoute
  appCollectionsDelinquentContractsIdRoute: typeof appCollectionsDelinquentContractsIdRoute
  appCollectionsDelinquentContractsIndexRoute: typeof appCollectionsDelinquentContractsIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appUnauthorizedRoute: appUnauthorizedRoute,
  appIndexRoute: appIndexRoute,
  appAddContractsContractIdRoute: appAddContractsContractIdRoute,
  appInstallmentTransactionIdRoute: appInstallmentTransactionIdRoute,
  appActiveContractsIndexRoute: appActiveContractsIndexRoute,
  appAddContractsIndexRoute: appAddContractsIndexRoute,
  appClosedContractsIndexRoute: appClosedContractsIndexRoute,
  appUploadContractsIndexRoute: appUploadContractsIndexRoute,
  appCollectionsDelinquentContractsIdRoute:
    appCollectionsDelinquentContractsIdRoute,
  appCollectionsDelinquentContractsIndexRoute:
    appCollectionsDelinquentContractsIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
